server:
  port: 3344

spring:
  application:
    name:  rkgspringcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/renkaige5/rkgspringcloud-config.git #GitHub上面的git仓库名字,http或者ssh都可以

